env:
  BUILD_JAVA_VERSION: '21'
jobs:
  analyze:
    if: github.event.workflow_run.head_repository.owner.login != 'dnsjava'
    name: Analyze Code
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: get_pr_number
      name: Download PR number artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: pr_number
        run_id: ${{ github.event.workflow_run.id }}
        workflow: ${{ github.event.workflow_run.name }}
    - continue-on-error: true
      id: pr_number
      name: Read Pull Request Number
      run: 'PR=$(cat pr_number.txt)

        echo "pr_number=${PR}" >> "$GITHUB_OUTPUT"

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: get_pr_data
      if: steps.get_pr_number.outputs.found_artifact
      name: Request PR data from GitHub API
      uses: octokit/request-action@v2.x
      with:
        full_name: ${{ github.event.repository.full_name }}
        number: ${{ steps.pr_number.outputs.pr_number }}
        route: GET /repos/{full_name}/pulls/{number}
    - continue-on-error: true
      name: Checkout PR
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.workflow_run.head_sha }}
        repository: ${{ github.event.workflow_run.head_repository.full_name }}
    - continue-on-error: true
      name: Make sure 'base' doesn't exist
      run: rm -rf base
      shell: bash
    - continue-on-error: true
      name: Checkout base
      uses: actions/checkout@v4
      with:
        path: base
        ref: ${{ fromJson(steps.get_pr_data.outputs.data).base.ref }}
        repository: ${{ github.event.repository.full_name }}
    - continue-on-error: true
      name: Get analysis data
      uses: ./base/.github/actions/prepare-analysis
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Run SonarQube
      run: 'cp -f base/pom.xml .

        mvn -B \

        -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }} \

        -Dsonar.pullrequest.key=${{ fromJson(steps.get_pr_data.outputs.data).number
        }} \

        -Dsonar.pullrequest.branch=${{ fromJson(steps.get_pr_data.outputs.data).head.ref
        }} \

        -Dsonar.pullrequest.base=${{ fromJson(steps.get_pr_data.outputs.data).base.ref
        }} \

        org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

        '
name: Analyze PR
on:
  repository_dispatch:
    types: trigger-ga___analyze.yml
permissions:
  checks: write
  contents: read
  pull-requests: read
